import { Product } from '../components/ProductDetailPage';

export const products: Product[] = [
  {
    id: 'prod-001',
    name: 'Fresh Tomatoes',
    nameUr: 'تازہ ٹماٹر',
    price: 120,
    originalPrice: 150,
    discount: 20,
    image: 'https://images.unsplash.com/photo-1700064165267-8fa68ef07167?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b21hdG9lcyUyMGZyZXNoJTIwcmVkfGVufDF8fHx8MTc2NDUyNjc0OXww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Vegetables',
    categoryUr: 'سبزیاں',
    description: 'Fresh, ripe tomatoes perfect for cooking and salads. Rich in vitamins and antioxidants.',
    descriptionUr: 'تازہ، پکے ٹماٹر کھانا پکانے اور سلاد کے لیے بہترین۔ وٹامنز اور اینٹی آکسیڈنٹس سے بھرپور۔',
    unit: 'kg',
    unitUr: 'کلو',
    inStock: true,
    rating: 4.5,
    reviews: 128,
    nutritionInfo: {
      calories: '18 kcal',
      protein: '0.9g',
      fat: '0.2g',
      carbs: '3.9g',
    },
  },
  {
    id: 'prod-002',
    name: 'Whole Milk 1L',
    nameUr: 'دودھ 1 لیٹر',
    price: 180,
    image: 'https://images.unsplash.com/photo-1635436338433-89747d0ca0ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaWxrJTIwYm90dGxlJTIwZGFpcnl8ZW58MXx8fHwxNzY0NDc5ODI0fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Dairy',
    categoryUr: 'دودھ کی مصنوعات',
    description: 'Fresh whole milk, rich and creamy. Perfect for drinking or cooking.',
    descriptionUr: 'تازہ مکمل دودھ، غنی اور کریمی۔ پینے یا کھانا پکانے کے لیے بہترین۔',
    unit: 'liter',
    unitUr: 'لیٹر',
    inStock: true,
    rating: 4.7,
    reviews: 245,
    nutritionInfo: {
      calories: '61 kcal',
      protein: '3.2g',
      fat: '3.3g',
      carbs: '4.8g',
    },
  },
  {
    id: 'prod-003',
    name: 'White Bread Loaf',
    nameUr: 'سفید روٹی',
    price: 90,
    originalPrice: 120,
    discount: 25,
    image: 'https://images.unsplash.com/photo-1634598603904-0a7516ec64b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aGl0ZSUyMGJyZWFkJTIwbG9hZnxlbnwxfHx8fDE3NjQ1MjMzNjJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Bakery',
    categoryUr: 'بیکری',
    description: 'Soft, fresh white bread loaf. Perfect for sandwiches and toast.',
    descriptionUr: 'نرم، تازہ سفید روٹی۔ سینڈوچ اور ٹوسٹ کے لیے بہترین۔',
    unit: 'loaf',
    unitUr: 'روٹی',
    inStock: true,
    rating: 4.3,
    reviews: 89,
    nutritionInfo: {
      calories: '265 kcal',
      protein: '9g',
      fat: '3g',
      carbs: '49g',
    },
  },
  {
    id: 'prod-004',
    name: 'Chicken Breast',
    nameUr: 'مرغی کا سینہ',
    price: 340,
    image: 'https://images.unsplash.com/photo-1633096013004-e2cb4023b560?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwYnJlYXN0JTIwbWVhdHxlbnwxfHx8fDE3NjQ0MjA3MzB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Meat',
    categoryUr: 'گوشت',
    description: 'Fresh, lean chicken breast. High in protein, low in fat.',
    descriptionUr: 'تازہ، کم چکنائی والا مرغی کا سینہ۔ پروٹین میں زیادہ، چکنائی میں کم۔',
    unit: 'kg',
    unitUr: 'کلو',
    inStock: true,
    rating: 4.8,
    reviews: 312,
    nutritionInfo: {
      calories: '165 kcal',
      protein: '31g',
      fat: '3.6g',
      carbs: '0g',
    },
  },
  {
    id: 'prod-005',
    name: 'Dalda Cooking Oil',
    nameUr: 'ڈالڈا تیل',
    price: 450,
    originalPrice: 500,
    discount: 10,
    image: 'https://images.unsplash.com/photo-1757801333068-d52a3e448cde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb29raW5nJTIwb2lsJTIwYm90dGxlJTIwZ29sZGVufGVufDF8fHx8MTc2NDUyNjc0OHww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Household',
    categoryUr: 'گھر کا سامان',
    description: 'Premium cooking oil for all your frying and cooking needs. Light and healthy.',
    descriptionUr: 'آپ کی تمام فرائی اور کھانا پکانے کی ضروریات کے لیے پریمیم کھانا پکانے کا تیل۔ ہلکا اور صحت بخش۔',
    unit: 'liter',
    unitUr: 'لیٹر',
    inStock: true,
    rating: 4.6,
    reviews: 198,
  },
  {
    id: 'prod-006',
    name: 'Desi Ghee',
    nameUr: 'دیسی گھی',
    price: 850,
    image: 'https://images.unsplash.com/photo-1732377448751-bb44ea81c5ac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnaGVlJTIwamFyJTIwYnV0dGVyfGVufDF8fHx8MTc2NDUyNDM5OXww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Dairy',
    categoryUr: 'دودھ کی مصنوعات',
    description: 'Pure desi ghee made from fresh butter. Rich in flavor and nutrients.',
    descriptionUr: 'تازہ مکھن سے بنا خالص دیسی گھی۔ ذائقے اور غذائیت سے بھرپور۔',
    unit: 'kg',
    unitUr: 'کلو',
    inStock: true,
    rating: 4.9,
    reviews: 421,
  },
  {
    id: 'prod-007',
    name: 'Fresh Potatoes',
    nameUr: 'تازہ آلو',
    price: 60,
    originalPrice: 80,
    discount: 25,
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwb3RhdG9lcyUyMHZlZ2V0YWJsZXxlbnwxfHx8fDE3NjQ1MjY3NTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Vegetables',
    categoryUr: 'سبزیاں',
    description: 'Fresh potatoes, versatile and nutritious. Perfect for any dish.',
    descriptionUr: 'تازہ آلو، ورسٹائل اور غذائیت سے بھرپور۔ کسی بھی ڈش کے لیے بہترین۔',
    unit: 'kg',
    unitUr: 'کلو',
    inStock: true,
    rating: 4.4,
    reviews: 156,
    nutritionInfo: {
      calories: '77 kcal',
      protein: '2g',
      fat: '0.1g',
      carbs: '17g',
    },
  },
  {
    id: 'prod-008',
    name: 'Red Onions',
    nameUr: 'لال پیاز',
    price: 100,
    originalPrice: 130,
    discount: 23,
    image: 'https://images.unsplash.com/photo-1668295037469-8b0e8d11cd2a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZWQlMjBvbmlvbnN8ZW58MXx8fHwxNzY0NDMxODgyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Vegetables',
    categoryUr: 'سبزیاں',
    description: 'Fresh red onions, crisp and flavorful. Essential for every kitchen.',
    descriptionUr: 'تازہ لال پیاز، کرکرا اور ذائقہ دار۔ ہر باورچی خانے کے لیے ضروری۔',
    unit: 'kg',
    unitUr: 'کلو',
    inStock: true,
    rating: 4.5,
    reviews: 203,
    nutritionInfo: {
      calories: '40 kcal',
      protein: '1.1g',
      fat: '0.1g',
      carbs: '9.3g',
    },
  },
  {
    id: 'prod-009',
    name: 'Natural Yogurt',
    nameUr: 'قدرتی دہی',
    price: 150,
    image: 'https://images.unsplash.com/photo-1763825613390-287a9db0803d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b2d1cnQlMjBib3dsJTIwZGFpcnl8ZW58MXx8fHwxNzY0NTI2NzUwfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Dairy',
    categoryUr: 'دودھ کی مصنوعات',
    description: 'Fresh, natural yogurt. Rich in probiotics and calcium.',
    descriptionUr: 'تازہ، قدرتی دہی۔ پروبائیوٹکس اور کیلشیم سے بھرپور۔',
    unit: 'kg',
    unitUr: 'کلو',
    inStock: true,
    rating: 4.6,
    reviews: 178,
    nutritionInfo: {
      calories: '59 kcal',
      protein: '3.5g',
      fat: '0.4g',
      carbs: '11g',
    },
  },
  {
    id: 'prod-010',
    name: 'Cheddar Cheese',
    nameUr: 'چیڈر پنیر',
    price: 420,
    originalPrice: 500,
    discount: 16,
    image: 'https://images.unsplash.com/photo-1709997460782-20dbad50ff53?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGVkZGFyJTIwY2hlZXNlJTIwc2xpY2VzfGVufDF8fHx8MTc2NDUyNjc1MXww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Dairy',
    categoryUr: 'دودھ کی مصنوعات',
    description: 'Premium cheddar cheese, perfect for sandwiches and cooking.',
    descriptionUr: 'پریمیم چیڈر پنیر، سینڈوچ اور کھانا پکانے کے لیے بہترین۔',
    unit: '250g',
    unitUr: '250 گرام',
    inStock: true,
    rating: 4.7,
    reviews: 134,
    nutritionInfo: {
      calories: '402 kcal',
      protein: '25g',
      fat: '33g',
      carbs: '1.3g',
    },
  },
  {
    id: 'prod-011',
    name: 'Basmati Rice',
    nameUr: 'باسمتی چاول',
    price: 280,
    image: 'https://images.unsplash.com/photo-1505216980056-a7b7b1c6e000?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXNtYXRpJTIwcmljZSUyMGdyYWluc3xlbnwxfHx8fDE3NjQ0ODMyODN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Groceries',
    categoryUr: 'گروسری',
    description: 'Premium quality basmati rice. Long grain and aromatic.',
    descriptionUr: 'پریمیم کوالٹی باسمتی چاول۔ لمبا دانہ اور خوشبودار۔',
    unit: 'kg',
    unitUr: 'کلو',
    inStock: true,
    rating: 4.8,
    reviews: 289,
    nutritionInfo: {
      calories: '130 kcal',
      protein: '2.7g',
      fat: '0.3g',
      carbs: '28g',
    },
  },
  {
    id: 'prod-012',
    name: 'Wheat Flour',
    nameUr: 'گندم کا آٹا',
    price: 140,
    originalPrice: 160,
    discount: 12,
    image: 'https://images.unsplash.com/photo-1760727466909-a73872aeecda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aGVhdCUyMGZsb3VyJTIwYmFnfGVufDF8fHx8MTc2NDQzMTg3N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Groceries',
    categoryUr: 'گروسری',
    description: 'Fine quality wheat flour for making soft rotis and bread.',
    descriptionUr: 'نرم روٹیاں اور روٹی بنانے کے لیے عمدہ کوالٹی کا گندم کا آٹا۔',
    unit: 'kg',
    unitUr: 'کلو',
    inStock: true,
    rating: 4.5,
    reviews: 412,
    nutritionInfo: {
      calories: '364 kcal',
      protein: '10g',
      fat: '1g',
      carbs: '76g',
    },
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter(p => p.category === category || p.categoryUr === category);
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase();
  return products.filter(
    p =>
      p.name.toLowerCase().includes(lowerQuery) ||
      p.nameUr.includes(query) ||
      p.category.toLowerCase().includes(lowerQuery) ||
      p.categoryUr.includes(query)
  );
}